name: Continuous Integration
on:
  workflow_dispatch:
jobs:
  build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.6]
        steps:
            - uses: actions/checkout@v2
            - name: S
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python-version }}
                architecture: x64
            - name: Run Test
              run: pip install pytest
            - name: Run2
              run: python -m unittest discover .
